version: '2'

services:
  db:
    image: postgres:12.4-alpine
    container_name: f-storage.db
    hostname: f-storage.db
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - 15432:5432
    env_file:
      - .env
